# Generated by Django 3.2.14 on 2022-07-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0003_auto_20220720_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ManyToManyField(to='seats.Seat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='showing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='seats.showing'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='showing',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='seats.event'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='seats.room'),
        ),
    ]
